# https://issuetracker.revi.xyz/u/dependabot
# for documentation link

version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    assignees:
      - 'revi'
    # Workflow files stored in the default location of `.github/workflows`.
    # You don't need to specify `/.github/workflows` for `directory`.
    # You can use `directory: "/"`.
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Asia/Seoul'
    target-branch: 'master'
    commit-message:
      prefix: 'CI(GitHub Actions)'
      include: 'scope'

  # Maintain dependencies for `npm` @ rootdir
  - package-ecosystem: 'npm'
    assignees:
      - 'revi'
    # npm package dependencies in the location of `/package.json`.
    directory: '/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Asia/Seoul'
    target-branch: 'master'
    commit-message:
      prefix: 'npm'
      prefix-development: 'npm(dev)'
      include: 'scope'

  # Maintain dependencies for `npm` @ Docusaurus
  - package-ecosystem: 'npm'
    assignees:
      - 'revi'
    # npm package dependencies in the location of `docusaurus/package.json`.
    directory: 'docusaurus/'
    schedule:
      interval: 'weekly'
      day: 'monday'
      time: '10:00'
      timezone: 'Asia/Seoul'
    target-branch: 'master'
    groups:
      docusaurus:
        patterns: ['@docusaurus/*']
      eslint:
        patterns: ['@eslint/*', 'eslint', 'eslint-*']
      react:
        patterns:
          ['@mdx-js/react', 'prism-react-renderer', 'react', 'react-dom']
    commit-message:
      prefix: 'docusaurus(npm)'
      prefix-development: 'docusaurus(npm-dev)'
      include: 'scope'
