# SPDX-FileCopyrightText: (C) 2024 Hong Yongmin <https://revi.xyz/>
#
# SPDX-License-Identifier: Apache-2.0

version = 1
SPDX-PackageName = "revi.xyz"
SPDX-PackageSupplier = "Hong Yongmin"

[[annotations]]
path = ".arc*"
precedence = "aggregate"
SPDX-FileCopyrightText = [
  "(C) 2014 Phacility, Inc.",
  "(C) 2021 Phorge Authors",
  "(C) 2024 Hong Yongmin <https://revi.xyz>"
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "See also https://we.phorge.it/source/phorge/browse/master/NOTICE"

[[annotations]]
path = [
  ".devcontainer/**/*.json",
  ".github/renovate.json",
  ".gitmodules",
  ".htmlvalidate.json",
  ".imgbotconfig",
  ".node-version",
  ".vscode/*.json",
  "package-lock.json",
  "package.json",
  "**/tsconfig.json"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Hong Yongmin <https://revi.xyz>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "docusaurus/i18n/ko/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Hong Yongmin <https://revi.xyz>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = [
  "docusaurus/static/_headers",
  "docusaurus/static/_redirects",
  "docusaurus/static/*.asc",
  "docusaurus/static/webfinger.json",
  "docusaurus/static/.well-known/**/*"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Hong Yongmin <https://revi.xyz>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docusaurus/static/fonts/0xProto/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2023, 0xType Project Authors (https://github.com/0xType)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = ["docusaurus/static/google*.html", "docusaurus/static/ads.txt"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docusaurus/static/img/bbip-bg.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2022 Bbip"
SPDX-License-Identifier = "LicenseRef-None"

[[annotations]]
path = "docusaurus/static/img/logo.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2022 시안"
SPDX-License-Identifier = "LicenseRef-None"

[[annotations]]
path = "docusaurus/static/img/by-nd.svg"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2014 Creative Commons"
SPDX-License-Identifier = "LicenseRef-None"
SPDX-FileComment = "Trademark: https://creativecommons.org/policies/"

[[annotations]]
path = "docusaurus/static/naver*.html"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Naver Corp."
SPDX-License-Identifier = "Apache-2.0"
