# SPDX-FileCopyrightText: (C) 2024 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

version = 1
SPDX-PackageName = "revi.xyz"
SPDX-PackageSupplier = "Hong Yongmin"

[[annotations]]
path = ".arc*"
precedence = "aggregate"
SPDX-FileCopyrightText = [
  "(C) 2014 Phacility, Inc.",
  "(C) 2021 Phorge Authors",
  "(C) 2024 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>",
]
SPDX-License-Identifier = "Apache-2.0"
SPDX-FileComment = "See also https://we.phorge.it/source/phorge/browse/master/NOTICE"

[[annotations]]
path = [
  ".devcontainer/**/*.json",
  ".github/renovate.json",
  ".gitmodules",
  ".htmlvalidate.json",
  ".imgbotconfig",
  ".jshintrc.json",
  ".node-version",
  ".vscode/*.json",
  "docusaurus/**/wrangler.toml",
  "package-lock.json",
  "Pipfile.lock",
  "**/package.json",
  "**/tsconfig.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>"
SPDX-License-Identifier = "Apache-2.0"

# i18n files

[[annotations]]
path = ["docusaurus/i18n/**/*"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>"
SPDX-License-Identifier = "Apache-2.0"

# static files

[[annotations]]
path = [
  "docusaurus/static/_headers",
  "docusaurus/static/_redirects",
  "docusaurus/static/*.asc",
  "docusaurus/static/img/emailexample.png",
  "docusaurus/static/.well-known/**/*",
  "docusaurus/static/webfinger.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docusaurus/static/fonts/0xProto/*"
precedence = "aggregate"
SPDX-FileCopyrightText = "Copyright (c) 2023, 0xType Project Authors (https://github.com/0xType)"
SPDX-License-Identifier = "OFL-1.1"

[[annotations]]
path = [
  "docusaurus/static/google*.html",
  "docusaurus/static/ads.txt",
  "docusaurus/static/app-ads.txt",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Google LLC"
SPDX-License-Identifier = "Apache-2.0"

[[annotations]]
path = "docusaurus/static/img/bbip-bg.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2022 Bbip"
SPDX-License-Identifier = "LicenseRef-None"

[[annotations]]
path = "docusaurus/static/img/logo.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2022 시안"
SPDX-License-Identifier = "LicenseRef-None"

[[annotations]]
path = ["docusaurus/static/img/by.svg", "docusaurus/static/img/by-nd.svg"]
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2014 Creative Commons"
SPDX-License-Identifier = "LicenseRef-None"
SPDX-FileComment = "Trademark: https://creativecommons.org/policies/"

[[annotations]]
path = "docusaurus/static/naver*.html"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Naver Corp."
SPDX-License-Identifier = "Apache-2.0"

# Blog

[[annotations]]
path = "docusaurus/blog/2022/*.png"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2022 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>"
SPDX-License-Identifier = ["LAL-1.3", "LicenseRef-CC-BY-2.0-KR"]

[[annotations]]
path = "docusaurus/blog/2023/*.jpeg"
precedence = "aggregate"
SPDX-FileCopyrightText = "(C) 2023 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>"
SPDX-License-Identifier = ["LAL-1.3", "LicenseRef-CC-BY-2.0-KR"]

[[annotations]]
path = "docusaurus/blog/2024/*.png"
precedencen = "aggregate"
SPDX-FileCopyrightText = "(C) 2024 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>"
SPDX-License-Identifier = ["LAL-1.3", "LicenseRef-CC-BY-2.0-KR"]
