---
# yaml-language-server: $schema=https://raw.githubusercontent.com/microsoft/azure-pipelines-vscode/master/service-schema.json
# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  - master

pool:
  vmImage: ubuntu-latest

strategy:
  matrix:
    node_20_x:
      node_version: 20.x
    node_22_x:
      node_version: 22.x

steps:
  - task: UseNode@1
    inputs:
      version: $(node_version)
    displayName: 'Install Node.js'
  - script: |
      npm ci
      npm run dbuild
    displayName: 'npm ci and build'
  - script: |
      npm run p:c .
    displayName: 'Prettier check'
  - script: |
      npm run lint:renovate
    displayName: 'Renovate config validator'
