---
name: 'Cloudflare Pages'

on:
  push:
    branches:
      - master
      - prod
    paths:
      - '.github/workflows/**'
      - '.github/dependabot.yml'
      - '.github/renovate.json'
      - 'docusaurus/**'
      - 'package.json'
      - 'package-lock.json'
  workflow_dispatch:

# prettier-ignore
env:
  IBM_TELEMETRY_DISABLED: true
  CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
  CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4
        with:
          fetch-depth: 0
      - name: 'Setup Node.js'
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v4
        with:
          node-version: 20
          cache: npm
      - name: 'Install dependencies'
        run: npm ci --omit=optional
      - name: 'Build website'
        run: npm run dbuild
      - name: 'Deploy to Cloudflare Pages (master)'
        if: github.ref_name == 'master'
        # yamllint disable-line rule:line-length
        run: npx wrangler pages deploy ${{ github.workspace }}/docusaurus/build --project-name=revi-xyz --branch master --commit-dirty=true
      - name: 'Deploy to Cloudflare Pages (prod)'
        if: github.ref_name == 'prod'
        # yamllint disable-line rule:line-length
        run: npx wrangler pages deploy ${{ github.workspace }}/docusaurus/build --project-name=revi-xyz --commit-dirty=true
