# SPDX-FileCopyrightText: (C) 2024 Hong Yongmin (https://revi.xyz/) <yewon@revi.email>
#
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

---
name: Cloudflare Pages

on:
  push:
    branches:
      - master
      - prod
    paths:
      - '.github/workflows/**'
      - .github/dependabot.yml
      - .github/renovate.json
      - 'docusaurus/**'
      - package.json
      - 'package-lock.json'
  workflow_dispatch:

# prettier-ignore
env:
  IBM_TELEMETRY_DISABLED: true
  TURBO_TELEMETRY_DISABLED: 1

jobs:
  build:
    name: Build Docusaurus
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        with:
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
        with:
          node-version-file: '.node-version'
          cache: npm
      - name: Set timezone to Asia/Seoul
        run: sudo timedatectl set-timezone Asia/Seoul
      - name: Install dependencies
        run: npm ci --omit=optional
      - name: Build website
        run: npm run dbuild
      - name: Deploy to Cloudflare Pages (master)
        if: github.ref_name == 'master'
        # yamllint disable-line rule:line-length
        run: npx wrangler pages deploy ${{ github.workspace }}/docusaurus/build --project-name=revi-xyz --branch master --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
      - name: Deploy to Cloudflare Pages (prod)
        if: github.ref_name == 'prod'
        # yamllint disable-line rule:line-length
        run: npx wrangler pages deploy ${{ github.workspace }}/docusaurus/build --project-name=revi-xyz --commit-dirty=true
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
